#! bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -s $DIR/.vimrc ~/.vimrc
sudo ln -s $DIR/.vimrc /root/.vimrc

ln -s $DIR/.tmux.conf ~/.tmux.conf
ls -s $DIR/.fish.config ~/.config/fish/config.fish
